services:
  health-journal-api:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - /home/joe/config/health-journal:/app/data
      - /home/joe/config/health-journal/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped

  health-journal-web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: unless-stopped